blogCambioClimatico/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
  	path('', views.Home_Noticias, name="home_noticias"),
  	path('cargar/', views.Cargar_noticia.as_view(), name ='cargar_noticia'),
  	path('Detalle/<int:pk>', views.Detalle_noticia, name ='detalle_noticia'),
  	path('Modificar/<int:pk>', views.Modificar_noticia.as_view(), name ='modificar_noticia'),
  	path('Borrar/<int:pk>', views.Borrar_noticia.as_view(), name ='borrar_noticia'),
]

blogCambioClimatico/apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = 'usuarios'

urlpatterns = [
  	path('Registro/', views.Registro.as_view(), name="registro_usuario"),
	path('Perfil/', views.Perfil.as_view(), name="perfil"),

]

blogCambioClimatico/blogCambioClimatico/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Home, name ='inicio'),
    path('contacto', views.Contacto, name ='contacto'),
    path('nosotros', views.Nosotros, name ='nosotros'),

    #APP NOTICIAS
    path('noticias/', include('apps.noticias.urls')),

    #APP USUARIOs
    path('Usuarios/', include('apps.usuarios.urls')),

    #APP COMENTARIOS
    path('Comentarios/', include('apps.comentarios.urls')),


    #LOGIN Y LOGOUT
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogCambioClimatico/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    
    <link rel="stylesheet" href="{% static 'css/forms.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/comentario.css' %}">
    
</head>
<body>
    <!-- Navbar -->
    <div class="container">
        <nav id="navbar" class="navbar fixed-top navbar-expand-lg navbar-dark" data-spy="affix">
            <div class="container-fluid">
                <a class="navbar-brand fw-bold" href="{% url 'inicio' %}">Portada</a>
                <a class="navbar-brand fw-bold" href="{% url 'noticias:home_noticias' %}">Noticias</a>
                <a class="navbar-brand fw-bold" href="{% url 'noticias:cargar_noticia' %}">Cargar Noticia</a>
                <a class="navbar-brand fw-bold" href="{% url 'contacto' %}">Contacto</a>
                <a class="navbar-brand fw-bold" href="{% url 'nosotros'%}">Nosotros</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto">
                        {% if user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'usuarios:perfil'%}">Perfil</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'logout'%}">Salir</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'login'%}">Ingresar</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'usuarios:registro_usuario' %}">Registrarme</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>

    <!-- Contenido principal -->
    <main class="contenidoPrincipal">
        {% block contenido %}
        {% endblock %}
    </main>


    <!-- Footer -->
    <footer class="footer card-footer pieDePagina">
        <div class="container my-5" >
            <footer class="text-center">
                <!-- Grid container -->
                <div class="container p-4 pb-0 d-flex align-items-center justify-content-center">
                    <h3 >
                        Redes Sociales
                    </h3>
                </div>
                <div>
                    <p>
                        Puedes seguirnos en nuestras redes sociales para enterarte de los ultimos acontecimientos sobre cambio climato en el mundo!.
                    </p>
                </div>
                <div class="container p-1 pb-0 d-flex align-items-center justify-content-center">
                    <!-- Section: Social media -->
                    <section class="mb-4">
                        <!-- Twitter -->
                        <a class="btn btn-primary btn-floating m-1 iconos" style="background-color: #55acee;" href="https://twitter.com/#"
                            rel="noopener noreferrer" target="_blank" role="button"><i class="fab fa-2x fa-twitter"></i></a>
    
                        <!-- Instagram -->
                        <a class="btn btn-primary btn-floating m-1 iconos" style="background-color: #ac2bac;" href="https://instagram.com/#"
                            rel="noopener noreferrer" target="_blank" role="button"><i class="fab fa-2x fa-instagram"></i></a>
        
                        <!-- Telegram -->
                        <a class="btn btn-primary btn-floating m-1 iconos" style="background-color: #229ED9    ;" href="https://t.me/#"
                            rel="noopener noreferrer" target="_blank" role="button"><i class="fab fa-2x fa-telegram"></i></a>
    
                        <!-- Facebook -->
                        <a class="btn btn-primary btn-floating m-1 iconos" style="background-color: #1877f2;" href="https://github.com/#"
                            rel="noopener noreferrer" target="_blank" role="button"><i class="fab fa-2x fa-facebook"></i></a>
                    </section>
                    <!-- Section: Social media -->
            </footer>
    
        </div>
        <!-- End of .container -->
    
    </footer>
<script src="{% static 'js/navbar.js' %}"></script>

</body>
</html>

blogCambioClimatico/templates/contacto.html
{% extends "base.html" %}


{% load static %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'css/news.css' %}">
<link rel="stylesheet" href="{% static 'css/contact.css' %}">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <h3 class="text-center titulo_secundario">
                    Contacto
                </h3>
                    <p class="text-center subtitulo_secundario">
                        ¿Tienes preguntas, comentarios o sugerencias?
                    </p>
                    <p class="text-center subtitulo_secundario">
                        ¡Nos encantaría escucharte!
                    </p>
                <div class="card_form">
                    <form class="form" method="post" action="{% url 'contacto' %}">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="nombre" class="form-label">Nombre</label>
                            <div class="nombre">
                                <input type="text" class="form-control" id="nombre">
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email</label>
                            <div class="email">
                                <input type="email" class="form-control" id="email">
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="telefono" class="form-label">Telefono</label>
                            <div class="telefono">
                                <input type="text" class="form-control" id="telefono">
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="asunto" class="form-label">Asunto</label>
                            <div class="asunto">
                                <input type="text" class="form-control" id="asunto">
                            </div>
                        </div>
                        <div class="mb-3">
                            <label for="mensaje" class="form-label">Mensaje</label>
                            <textarea class="form-control" id="mensaje" rows="3"></textarea>
                        </div>
                        <button type="submit" class="btn btn-primary btn_send">Enviar</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

blogCambioClimatico/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block contenido %}

<!-- Portada -->
<header id="portada" class="masthead" style="background-image: url({% static 'img/portada.png' %})">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-10 col-lg-8 col-xl-7">
                <div class="site-heading">
                    <h1>Blog sobre cambio climático</h1>
                    <span class="subheading"></span>
                </div>
            </div>
        </div>
    </div>
</header>



<!-- Categorías -->
<section id="categorias" class="bg-light">
    <div class="container text-center">
        <p class="text-center titulo_secundario">Categorías</p>
        <br>
        <div class="row">
            <div class="col-md-4">
                <h3>Cambio Climático</h3>
                <p>
                    Descubre las últimas investigaciones y noticias sobre el cambio climático global. Exploraremos los impactos, las causas subyacentes y las posibles soluciones para abordar este desafío crítico.
                </p>
            </div>
            <div class="col-md-4">
                <h3>Soluciones Sostenibles</h3>
                <p>
                    Explora prácticas y proyectos que contribuyen a un futuro más ecológico y sostenible. Desde tecnologías renovables hasta iniciativas comunitarias, analizaremos cómo podemos trabajar juntos para un mundo más verde.
                </p>
            </div>
            <div class="col-md-4">
                <h3>Impacto Ambiental</h3>
                <p>
                    Analiza el impacto ambiental de diversas actividades humanas y cómo podemos mitigarlo. Desde la huella de carbono hasta la conservación de la biodiversidad, examinaremos las acciones para preservar nuestro planeta.
                </p>
            </div>
            <div class="col-md-4">
                <h3>Innovación Tecnológica</h3>
                <p>
                    Exploraremos las últimas innovaciones tecnológicas diseñadas para abordar los desafíos del cambio climático. Desde inteligencia artificial hasta energías limpias, seguimos de cerca el papel de la tecnología en la sostenibilidad.
                </p>
            </div>
            <div class="col-md-4">
                <h3>Políticas Ambientales</h3>
                <p>
                    Examina las políticas gubernamentales y las iniciativas internacionales para combatir el cambio climático. Analizaremos los enfoques legislativos y los acuerdos internacionales que buscan garantizar un futuro más sostenible.
                </p>
            </div>
            <div class="col-md-4">
                <h3>Educación Ambiental</h3>
                <p>
                    Conoce más sobre programas educativos y recursos destinados a aumentar la conciencia ambiental. Desde actividades escolares hasta plataformas en línea, exploraremos cómo la educación puede impulsar un cambio positivo.
                </p>
            </div>
            <!-- Puedes agregar más categorías según tus necesidades -->
        </div>
    </div>
</section>

<!-- Últimas Entradas Destacadas -->
<section id="ultimas-entradas" class="bg-light">
    <div class="container text-center">
        <p class="titulo_secundario">Acontecimientos relevantes</p>
        <br>
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <img src="{% static 'img/tierra1.jpg' %}" class="card-img-top" alt="Imagen de la entrada">
                    <div class="card-body">
                        <h3 class="card-title">Consecuencias del calentamiento global: ¿que produce el calentamiento global?</h3>
                        <p class="card-text">
                            El calentamiento global está ocurriendo más rápido de lo que esperaban los científicos. De hecho, algunos impactos ya están amenazando al medio ambiente y ponen en peligro la supervivencia de la flora y la fauna, incluso el ser humano.
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="{% static 'img/tierra2.png' %}" class="card-img-top" alt="Imagen de la entrada">
                    <div class="card-body">
                        <h3 class="card-title">Calcular tu huella de carbono</h3>
                        <p class="card-text">
                            Mitigar los efectos del calentamiento global significa adaptar su estilo de vida a la situación actual, reduciendo y limitando las emisiones de gases de efecto invernadero. Para ello, el primer paso es tomar conciencia de su propia huella de carbono.
                            <ol>
                                <li>El cálculo de la huella de carbono es el primer paso para reducirla: identificar las principales fuentes de emisiones de gases de efecto invernadero en nuestra vida cotidiana y adaptar así nuestro estilo de vida para minimizar su impacto de carbono en el medio ambiente;</li>
                                <li>La reducción de las emisiones de gases de efecto invernadero es muy importante para luchar contra el calentamiento global: optimizar el consumo de energía, reducir nuestra huella digital de carbono y promover el transporte sostenible;</li>
                                <li>La compensación de sus emisiones de carbono mediante la financiación de proyectos ambientales con el fin de reducir las emisiones de gases de efecto invernadero a la atmósfera y avanzar así hacia la neutralidad del carbono.</li>
                            </ol>
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <img src="{% static 'img/Tierra3.jpg' %}" class="card-img-top" alt="Imagen de la entrada">
                    <div class="card-body">
                        <h3 class="card-title">Consecuencias y efectos del calentamiento global</h3>
                        <p class="card-text">
                            El calentamiento global ya no es un problema del futuro: es una situación que debemos parar de inmediato o la destrucción del planeta será irreversible. Sequías, huracanes, hambre, pobreza y destrucción: estas son algunas de las terribles consecuencias que el calentamiento global provoca en nuestro planeta. Y en nuestra mano está participar activamente para frenar sus efectos si queremos que las siguientes generaciones hereden un mundo tal y como lo conocemos hoy. O incluso mejor.
                            <ol>
                                <li>Muchas especies de animales están viendo cómo su clima actual desaparece y no son capaces de adaptarse a cambios tan rápidamente.</li>
                                <li>El aumento de temperatura del mar hace que los huracanes se vuelvan más violentos.</li>
                                <li>La acumulación de gases contaminantes hace que las temperaturas aumenten cada vez más y que los climas cambien: esto provoca sequías y, además, aumenta el riesgo de incendios que conllevan la deforestación y la desertización del planeta.</li>
                            </ol>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

blogCambioClimatico/templates/nosotros.html
{% extends "base.html" %}

{% load static %}

{% block contenido %}
<link rel="stylesheet" href="{% static 'css/us.css' %}">

<!-- Acerca de Nosotros -->
<section id="acerca-de">
    <div class="container text-center col-md-12 mt-5">
        <h2>Acerca de Nosotros</h2>
        <p>Bienvenido a nuestro blog dedicado a informar y concientizar sobre el cambio climático. Nuestro objetivo es proporcionar información relevante y soluciones para un futuro sostenible.</p>
        <p>Somos un equipo multidisciplinario de expertos en climatología, ecología, y sostenibilidad comprometidos con la preservación del medio ambiente y la difusión de conocimientos para inspirar el cambio.</p>
        <p>Nuestra misión es abordar críticamente los desafíos ambientales actuales, ofrecer análisis científicos y tecnológicos, y fomentar la adopción de prácticas sostenibles para mitigar el cambio climático.</p>
        <p>Trabajamos en colaboración con instituciones líderes, investigadores y defensores del medio ambiente para proporcionar contenido confiable y actualizado.</p>
        <!-- Comentario: Puedes personalizar aún más la información técnica sobre tu equipo y su enfoque aquí -->
    </div>
</section>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <img src="{% static 'img/Tatiana_G_R.jpeg' %}" class="card-img-top" alt="Integrante 1">
                <div class="card-body">
                    <h5 class="card-title">Gimenez Rios Tatiana Tamara</h5>
                    <p class="card-text">Hola! Soy Tatiana. Tengo 35 años, soy mamá de una hermosa niña. Recientemente recibida de la tecnicatura en programación y estudiante avanzada de la carrera de Contadora Pública. Ahora cursando el informatorio, dispuesta a aprender a programar!!!</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <img src="{% static 'img/els.jpg' %}" class="card-img-top" alt="Integrante 2">
                <div class="card-body">
                    <h5 class="card-title">Stride Eric</h5>
                    <p class="card-text">Hola, mi nombre es Eric, tengo 29 años y soy estudiante avanzado de Ingenieria en Sistemas de Informacion en la UTN Facultad regional de Resistencia.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <img src="{% static 'img/Nico_Tom.jpg' %}" class="card-img-top" alt="Integrante 3">
                <div class="card-body">
                    <h5 class="card-title">Tomadin Nicolás Adrián</h5>
                    <p class="card-text">Hola a todos, mi nombre es Tomadin, Nicolás Adrián, tengo 28 años y actualmente estoy inmerso en mi viaje académico. Soy estudiante de Ingeniería en Sistemas de Información en la UTN FRRe. Me apasiona la programacion y estoy emocionado por aprender y crecer en este campo. ¡Gracias por la oportunidad de compartir un poco sobre mí! </p>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>

{% endblock %}