blogCambioClimatico/apps/comentarios/urls.py
from django.urls import path
from . import views

app_name = 'comentarios'

urlpatterns = [
  	path('agergar/<int:pk>',views.Agregar_Comentario, name = 'agregar'),
  	path('Borrar/<int:pk>', views.BorrarComentario.as_view(), name="borrar_comentario"),
	path('Modificar/<int:pk>', views.ModificaComentario.as_view(), name="modificar_comentario"),
]

blogCambioClimatico/apps/noticias/urls.py
from django.urls import path
from . import views

app_name = 'noticias'

urlpatterns = [
  	path('', views.Home_Noticias, name="home_noticias"),
  	path('cargar/', views.Cargar_noticia.as_view(), name ='cargar_noticia'),
  	path('Detalle/<int:pk>', views.Detalle_noticia, name ='detalle_noticia'),
  	path('Modificar/<int:pk>', views.Modificar_noticia.as_view(), name ='modificar_noticia'),
  	path('Borrar/<int:pk>', views.Borrar_noticia.as_view(), name ='borrar_noticia'),
]

blogCambioClimatico/blogCambioClimatico/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', views.Home, name ='inicio'),
    path('contacto', views.Contacto, name ='contacto'),
    path('nosotros', views.Nosotros, name ='nosotros'),

    #APP NOTICIAS
    path('noticias/', include('apps.noticias.urls')),

    #APP USUARIOs
    path('Usuarios/', include('apps.usuarios.urls')),

    #APP COMENTARIOS
    path('Comentarios/', include('apps.comentarios.urls')),


    #LOGIN Y LOGOUT
    path('login/',auth.LoginView.as_view(template_name='usuarios/login.html'),name='login'),
    path('logout/',auth.LogoutView.as_view(),name="logout"),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogCambioClimatico/apps/noticias/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Categoria(models.Model):
	nombre = models.CharField(max_length = 100)

	def __str__(self):
		return self.nombre

class Noticia(models.Model):

	creado = models.DateTimeField(
		'creado',
		auto_now_add=True
	)
	modificado = models.DateTimeField(
		'modificado',
		auto_now=True
	)
	titulo = models.CharField(max_length = 250)
	contenido = models.TextField()
	#para usar ImegeField, necesito tener instalado la libreria pillow
	#pip install pillow
	imagen = models.ImageField(upload_to = 'noticias')
	categoria = models.ForeignKey(Categoria, on_delete = models.CASCADE)
	usuario = models.ForeignKey(User, on_delete = models.CASCADE)
	def __str__(self):
		return self.titulo

blogCambioClimatico/apps/noticias/forms.py
from django import forms
from .models import Noticia


class Formulario_Noticia(forms.ModelForm):

	class Meta:
		model = Noticia
		fields = ['titulo','contenido','imagen','categoria']

class Formulario_Modificar_Noticia(forms.ModelForm):

	class Meta:
		model = Noticia
		fields = ['contenido','imagen','categoria']

blogCambioClimatico/apps/noticias/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy

from .models import Noticia, Categoria
from .forms import Formulario_Noticia, Formulario_Modificar_Noticia

from apps.comentarios.models import Comentario

from django.http import HttpResponseRedirect

# CONTROLA SI EL USUARIO ESTA LOGEADO EN UNA VISTA BASADA EN CLASES
from django.contrib.auth.mixins import LoginRequiredMixin
# CONTROLA SI EL USUARIO ESTA LOGEADO EN UNA VISTA BASADA EN FUNCIONEs
from django.contrib.auth.decorators import login_required

# CONTROLA QUE EL USUARIO SEA STAFF VISTA BASADA EN FuNCION
from django.contrib.admin.views.decorators import staff_member_required
# CONTROLA QUE EL USUARIO SEA STAFF PARA VISTA BASADA EN CLASE
from django.contrib.auth.mixins import UserPassesTestMixin


# Vasta Basada en funciones
def Home_Noticias(request):
	contexto = {}
	cat = Categoria.objects.all()
	contexto['categorias'] = cat

	# CAPTURAR FILTROS
	filtro = request.GET.get('categoria', None)
	orden = request.GET.get('orden', None)
	query = request.GET.get('q', None)

	# FILTRAR POR CATEGORIA
	if not filtro or filtro == '0':
		todas = Noticia.objects.all()
	else:
		categoria_seleccionada = Categoria.objects.get(pk=filtro)
		todas = Noticia.objects.filter(categoria=categoria_seleccionada)

	# ORDENAR POR FECHA
	if orden == "reciente":
		todas = todas.order_by('creado')
	elif orden == 'antiguo':
		todas = todas.order_by('-creado')

	# ORDENAR POR TITULO
	if orden == 'a-z':
		todas = todas.order_by('titulo')
	elif orden == 'z-a':
		todas = todas.order_by('-titulo')

	# BUSQUEDA POR TITULO
	if query:
		todas = todas.filter(titulo__icontains=query)

	contexto['noticias'] = todas

	return render(request, 'noticias/home_noticias.html', contexto)


#ACLARACION
'''
si bien en la vista armo un diccionario del tipo
{noticias: todas_noticias, fecha: '28-11-2023'}
en el template resivo variables separadas, una por cada clave, la cual contiene como valor
el valor de la clave
EJ, recibo 2 variales distintas, cuyo nombre es igual a la clave
noticias = todas_noticias
fecha = '28-11-2023'
'''

#VISTA BASADA EN CLASE
class Home_Noticias_clase(ListView):
	model = Noticia
	template_name = 'noticias/home_noticias.html'
	context_object_name = 'noticias'

class Cargar_noticia(CreateView):
	model = Noticia
	template_name = 'noticias/cargar_noticia.html'
	form_class = Formulario_Noticia
	success_url = reverse_lazy('noticias:home_noticias')
	
	def form_valid(self, form):
		noticia = form.save(commit=False)
		noticia.usuario = self.request.user
		return super(Cargar_noticia, self).form_valid(form)

class Modificar_noticia(UpdateView):
	model = Noticia
	template_name = 'noticias/modificar_noticia.html'
	form_class = Formulario_Modificar_Noticia
	success_url = reverse_lazy('noticias:home_noticias')

class Borrar_noticia(DeleteView):
	model = Noticia
	success_url = reverse_lazy('noticias:home_noticias')

#ORM
# CONSULTA PARA TRAER TODOS LOS DATOS
# select * from Noticia  SQL
# Noticia.objects.all()   ORM

#CONSuLTA PARA TRAER SOLO UN DATO (POR CLAVE)
# select * from Noticia where id = algo    SQL
# Noticia.objects.get(id = algo)		ORM

#CONSuLTA PARA TRAER SOLO Algunos datos (POR filtro)
# select * from Noticia where categororia = deportes
# Noticia.objects.filter(categoria = deportes)

def Detalle_noticia(request, pk):
	ctx = {}
	n = Noticia.objects.get(pk = pk)
	ctx['noticia'] = n

	com = Comentario.objects.filter(noticia = n)
	ctx['comentarios'] = com
	return render(request,'noticias/detalle_noticia.html', ctx)

blogCambioClimatico/templates/noticias/cargar_noticia.html
{% extends "base.html" %}


{% load static %}

{% block contenido  %}
<link rel="stylesheet" href="{% static 'css/news.css' %}">
{% if user.is_authenticated %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <form action="" method="post" enctype="multipart/form-data" class="container">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12 mt-4">
                                <h3 class="text-center titulo_secundario">Crea tu noticia</h3>
                            </div>
                        </div>
                    </div>
                    <div class="card_form">
                        <div class="form-group">
                            <label for="titulo">Titulo</label>
                            <div class="titulo">
                                {{ form.titulo }}
                        </div>
                        <div class="form-group">
                            <label for="contenido">Descripcion</label>
                            <div class="contenido">
                                {{ form.contenido }}
                        </div>
                        <div class="form-group">
                            <label for="imagen">Imagen</label>
                            <div class="imagen">
                                {{ form.imagen }}
                        </div>
                        <div class="form-group">
                            <label for="categoria">Categoria</label>
                            <div class="categoria">
                                {{ form.categoria }}
                        </div>
                        
                        <input type="submit" value="Crear" class="btn btn-primary btn_send">
                    </div>  
                </form>
            </div>
        </div>
{% else %}
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-4">
    <h1>Debes estar logueado para crear una noticia</h1>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

blogCambioClimatico/templates/noticias/detalle_noticia.html
{% extends 'base.html' %}

{% block contenido %}
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md-8">
			<h1 class="text-center titulo_secundario">Detalle de {{noticia.titulo}}</h1>
			<div class="card">
				<div class="card-body">
					<p><strong>TITULO:</strong> {{noticia.titulo}}</p>
					<p><strong>CONTENIDO:</strong> {{noticia.contenido}}</p>
					<p class="img_detalle_noticia"><img src="{{noticia.imagen.url}}" class="img-fluid" alt="Noticia Imagen"></p>
				</div>
			</div>
			<hr>
			<h4 class="text-center subtitulo_secundario">COMENTARIOS</h4>
			{% for c in comentarios %}
				<div class="card mb-3 card_comentario">
					<div class="card-body">
						<a class="comentario_usuario">{{c.usuario}}</a>: 
						<a class="comentario_texto">{{c.texto}}</a> 
						{% if request.user == c.usuario or request.user.is_staff %} 
							<a href="{% url 'comentarios:borrar_comentario' c.pk%}"><i class="fas fa-times icono_borrar_comentario"></i></a> <a href="{% url 'comentarios:modificar_comentario' c.pk%}"><i class="fas fa-edit icono_editar_comentario"></i></a>
						{% endif %}
					</div>
				</div>
			{% endfor %}
			{% if request.user.is_authenticated %}
				<form method="POST" action="{% url 'comentarios:agregar' noticia.pk %}" class="form_comentario">
					{% csrf_token %}
					<div class="form-group row">
						<div class="col-9">
							<textarea class="form-control" name="comentario"></textarea>
						</div>
						<div class="col-3">
							<button type="submit" class="btn btn_comentar">COMENTAR</button>
						</div>
					</div>
				</form>
			{% endif %}
			<div style="height: 100px;"></div>
		</div>
	</div>
</div>
{% endblock contenido %}

blogCambioClimatico/templates/noticias/home_noticias.html
{% extends "base.html" %}

{% load static %}


{% block contenido %}
<!--<link rel="stylesheet" href="{% static 'css/filter.css' %}"> -->
<link rel="stylesheet" href="{% static 'css/cards.css' %}">
<link rel="stylesheet" href="{% static 'css/cardNews.css' %}">

    <div class="container">
        <div class="row text-center">
            <p class="titulo_principal">Noticias</p>
        </div>
        <div class="row text-center">
            <p class="subtitulo_principal">Estas son las noticias mas relevantes hasta la actualidad</p>
        </div>
        <!--Filtro-->
        <div class="row g-0">
            <div class="col-sm-6 col-md-8">
                <!--<div class="filtro-container "> -->
                    <div class="input-group">
						<form method="GET" action="{% url 'noticias:home_noticias' %}">
                            <div class="row align-items-end">
                                <div class="col-10">
                                    <input type="text" class="form-control" placeholder="Buscar" aria-label="Buscar" aria-describedby="button-addon2" name="q" value="{{ query }}">
                                </div>
                                <div class="col-2">
                                    <button class="btn" type="submit" id="button-addon2">Buscar</button>
                                </div>
                            </div>
						</form>
                    </div>
            </div>
            <div class="col-sm-6 col-md-4">
                <div class="row align-items-end rowDropdown">
                    <div id="filtroDropdown" class="dropdown filtro-dropdown col">
                        <button class="btn dropdown-toggle" type="button" id="filtroDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                            Todas
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="filtroDropdown">

                            {% if "?" in request.get_full_path %}
                                <li><a class="dropdown-item" href="{{ request.get_full_path }}&categoria=0">Todas</a></li>
                                {% for c in categorias %}
                                    <li><a class="dropdown-item" href="{{ request.get_full_path }}&categoria={{c.id}}">{{c.nombre}}</a></li>
                                {% endfor %}
                            {% else %}
                                <li><a class="dropdown-item" href="?categoria=0">Todas</a></li>
                                {% for c in categorias %}
                                    <li><a class="dropdown-item" href="?categoria={{c.id}}">{{c.nombre}}</a></li>
                                {% endfor %}
                            {% endif %}
                                                        
                        </ul>
                    </div>
                    <div id="filtroDropdown" class="dropdown filtro-dropdown col">
                        <button class="btn dropdown-toggle" type="button" id="filtroDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                            {% if "?" in request.get_full_path %}
                                {% if request.GET.orden == "reciente" %}
                                    Mas reciente
                                {% elif request.GET.orden == "antiguo" %}
                                    Mas antiguo
                                {% elif request.GET.orden == "a-z" %}
                                    a-z
                                {% elif request.GET.orden == "z-a" %}
                                    z-a              
                                {% else %}
                                    Mas reciente
                                {% endif %}
                            {% else %}
                                Mas reciente
                            {% endif %}
                        </button>
                        <ul class="dropdown-menu" aria-labelledby="filtroDropdown">
                            <!--
                            <li><a class="dropdown-item" href="#" data-value="default" >Mas reciente</a></li>
                            <li><a class="dropdown-item" href="#" data-value="1">Mas antiguo</a></li>
                            -->
                            {% if "?" in request.get_full_path %}
                                <li><a class="dropdown-item" href="{{ request.get_full_path }}&orden=reciente">Mas reciente</a></li>
                                <li><a class="dropdown-item" href="{{ request.get_full_path }}&orden=antiguo">Mas antiguo</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="?orden=reciente">Mas nuevo</a></li>
                                <li><a class="dropdown-item" href="?orden=antiguo">Mas antiguo</a></li>
                            {% endif %}
                            {% if "?" in request.get_full_path %}
                                <li><a class="dropdown-item" href="{{ request.get_full_path }}&orden=a-z">a-z</a></li>
                                <li><a class="dropdown-item" href="{{ request.get_full_path }}&orden=z-a">z-a</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="?orden=a-z">a-z</a></li>
                                <li><a class="dropdown-item" href="?orden=z-a">z-a</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                <!--</div> -->
            </div>
        </div>

        <div class="row row-cols-1 row-cols-md-3 g-4 divForNoticias">
            {% for noticia in noticias %}
                <div class="col">
                    <div class="card h-100 cardNoticia">
                        <div class="card-header text-center">
                            <h5 class="card-title">{{ noticia.titulo }}</h5>
                        </div>
                        {% if noticia.imagen %}
                            <a href="{% url 'noticias:detalle_noticia' noticia.pk %}">
                                <img src="{{ noticia.imagen.url }}" class="card-img-top" alt=""> 
                            </a>
                        {% else %}
                            <img src="{% static 'img/imgNotFound.jpg' %}" class="card-img-top" alt="..."> 
                        {% endif %}
                        <div class="card-body">
                            <!--<h5 class="card-title">{{ noticia.titulo }}</h5>-->
                            <p class="card-text">{{ noticia.contenido }}</p>
                        </div>
                        <div class="card-footer text-center">
                            <div>
                                <small style="color: black; text-decoration: underline;">Fecha de publicación</small>:
                                <small class="text-body-secondary">{{noticia.creado}}</small>
                            </div>
                            <div>
                                <small style="color: black; text-decoration: underline;">Autor</small>:
                                <small class="text-body-secondary">{{noticia.usuario}}</small>
                            </div>
                            <div>
                                <small style="color: black; text-decoration: underline;">Categoria</small>:
                                <small class="text-body-secondary">{{noticia.categoria}}</small>
                            </div>
                        </div>
                        <div class="card-footer text-center">
                            <div class="row">
                                <div class="col">
                                    <a class="detalleNoticia" href="{% url 'noticias:detalle_noticia' noticia.pk %}">Leer más</a>
                                </div>
                            {% if request.user == n.usuario or request.user.is_staff %}
                                <div class="col">
                                    <a class="modificarNoticia" href="{% url 'noticias:modificar_noticia' noticia.pk %}">Modificar</a>
                                </div>
                                <div class="col">
                                    <a class="borrarNoticia" href="{% url 'noticias:borrar_noticia' noticia.pk %}">Borrar</a>
                                </div>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    

    </div>



    <script>
        //defectValue.js

        document.addEventListener('DOMContentLoaded', function () {
          // Obtener todos los dropdowns en la página
          var dropdowns = document.querySelectorAll('.filtro-dropdown');
      
          // Iterar sobre cada dropdown
          dropdowns.forEach(function(dropdown) {
            // Obtener elementos específicos de cada dropdown
            var dropdownButton = dropdown.querySelector('.dropdown-toggle');
            var dropdownItems = dropdown.querySelectorAll('.dropdown-item');
      
            // Asignar evento de clic a cada elemento del dropdown
            dropdownItems.forEach(function(item) {
              item.addEventListener('click', function() {
                // Obtener el valor de la opción clickeada
                var selectedValue = item.getAttribute('data-value');
      
                // Establecer la clase 'active' en la opción clickeada
                dropdownItems.forEach(function(item) {
                  item.classList.remove('active');
                });
                item.classList.add('active');
      
                // Actualizar el texto del botón con la opción clickeada
                dropdownButton.textContent = item.textContent;
              });
            });
      
            // Establecer la opción por defecto al cargar la página
            var defaultOptionValue = "default"; // Cambia esto al valor que desees seleccionar por defecto
            var defaultOption = dropdown.querySelector('.dropdown-menu [data-value="' + defaultOptionValue + '"]');
            defaultOption.classList.add('active');
            dropdownButton.textContent = defaultOption.textContent;
          });
        });
      </script>
      
      
                
{% endblock %}

blogCambioClimatico/templates/noticias/modificar_noticia.html
{% extends "base.html" %}

{% load static %}

{% block contenido %}
    <link rel="stylesheet" href="{% static 'css/news.css' %}">
    
    {% if user.is_authenticated %}
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <form action="" method="post" enctype="multipart/form-data" class="container">
                        {% csrf_token %}
                        <div class="container">
                            <div class="row">
                                <div class="col-md-12 mt-4">
                                    <h3>Modificar Noticia</h3>
                                </div>
                            </div>
                        </div>
                        <div class="card_form">
                            <div class="form-group">
                                <label for="titulo">Título:</label>
                                <input type="text" id="id_titulo" name="titulo" value="{{ form.titulo.value }}" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="contenido">Descripción:</label>
                                <div class="contenido">
                                    {{ form.contenido }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="imagen">Imagen</label>
                                <div class="imagen">
                                    {{ form.imagen }}
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="categoria">Categoría</label>
                                <div class="categoria">
                                    {{ form.categoria }}
                                </div>
                            </div>
                            
                            <input type="submit" value="Guardar Cambios" class="btn btn-primary btn_send">
                        </div>  
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        <div class="container">
            <div class="row">
                <div class="col-md-12 mt-4">
                    <h1>Debes estar logueado para modificar una noticia</h1>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}

blogCambioClimatico/templates/noticias/noticia_confirm_delete.html
{% extends 'base.html' %}

{% block contenido %}
  
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-4">
      <div class="card">
        <form method="post" action="{% url 'noticias:borrar_noticia' pk=object.pk %}" class="confirmation-form">
          {% csrf_token %}
          <p>Estas por eliminar esta noticia:</p>
		  <p style="padding-left: 1rem;">{{ object }}</p>
          <div class="form-group row text-center">
			<p class="text-center">¿Deseas eliminarla?</p>
			<div class="container px-4">
				<div class="row gx-5">
					<div class="col">
						<button type="submit" class="btn btn_delete">CONFIRMAR</button>
					</div>
					<div class="col">
						<a href="#" onclick="window.history.back(); return false;" class="btn btn_cancel">CANCELAR</a>
					</div>
				</div>
			</div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock contenido %}